[package]
name = "payroll-http"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
threadpool = { path = "../threadpool" }
