FROM rust:latest AS builder

WORKDIR /work/
COPY . /work/
RUN cargo update
RUN cargo build --release

FROM debian:sid-slim

RUN apt update && apt install -y tini

COPY --from=builder /work/target/release/payroll-web /usr/bin/payroll-web

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["payroll-web", "-h", "0.0.0.0", "-p", "3000"]
