FROM rust:latest AS builder

WORKDIR /work/
COPY . /work/
RUN cargo update
RUN cargo build --release

FROM debian:sid-slim

COPY --from=builder /work/target/release/payroll-cli /usr/bin/payroll-cli
CMD ["payroll-cli", "-h"]
